### ISSUE TITLE
Struct bug

### ISSUE THREAD

**Issue by Angluca** [ocen-lang/ocen#4]
I'm newbie have test how to set comptime static var in struct, So ...
```rust
struct Test {
    let var: u32 //  if has const or let building no error, But always loop can't exits must kill
}
```

**Comment by mustafaquraish** [comment]
Parsing is still not super robust... I suspect there's other cases where we might infinite loop too. Thanks for pointing this out. Feel free to reach out on Discord (@segfault404) if you see anything else, more than happy to chat about any feedback you have!
